# Generated by Django 5.2.4 on 2025-07-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
