# Generated by Django 5.2.4 on 2025-07-23 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lessons_course"),
        ("users", "0004_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_lessons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_payments",
                to="materials.lessons",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
