version: '3.9'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    restart: always

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    restart: always

  app:
    image: ghcr.io/hi-techshotgun/djangorest_hw:latest
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_worker:
    image: ghcr.io/hi-techshotgun/djangorest_hw:latest
    restart: always
    command: celery -A config worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    image: ghcr.io/hi-techshotgun/djangorest_hw:latest
    restart: always
    command: celery -A config beat -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data: