# Generated by Django 5.2.4 on 2025-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=1000, verbose_name="Цена курса"),
        ),
    ]
