# Generated by Django 5.2.4 on 2025-08-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_last_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessons",
            options={
                "ordering": ("pk",),
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
