name: Django CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Клонирование репозитория
      uses: actions/checkout@v4

    - name: 2. Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 3. Установка Poetry
      run: pipx install poetry

    - name: 4. Установка зависимостей проекта
      run: poetry install --no-interaction --no-root

    - name: 5. Запуск тестов
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

        DEBUG: "False"

        NAME: "test_db"
        USER: "test_user"
        HOST: "localhost"
        PORT: "5432"

        REDIS_URL: "redis://localhost:6379"

        EMAIL_HOST: "localhost"
        EMAIL_PORT: "1025"
        EMAIL_USE_TLS: "False"
        EMAIL_USE_SSL: "False"
        EMAIL_HOST_USER: "test@example.com"
      run: |
        poetry run python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: 1. Деплой на сервер
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}

        script: |
          cd ~/DjangoRest_HW 
          
          git pull origin main
          
          /home/${{ secrets.SSH_USERNAME }}/.local/bin/poetry install --no-interaction
          
          /home/${{ secrets.SSH_USERNAME }}/.local/bin/poetry run python manage.py migrate
          
          /home/${{ secrets.SSH_USERNAME }}/.local/bin/poetry run python manage.py collectstatic --noinput
          
          sudo systemctl restart gunicorn.service 
          
          echo "✅ Деплой успешно завершен!"